import type { Client, CalendarItem } from "./types";
import { DEFAULT_SCOPE_TEMPLATES } from "./types";

const mkScope = (clientId: string) =>
  (["social", "seo", "email", "paid"] as const).flatMap((mod) =>
    DEFAULT_SCOPE_TEMPLATES[mod].map((tpl, i) => ({
      id: `${clientId}-${mod}-${i}`,
      module: mod,
      label: tpl.label,
      unit: tpl.unit,
      committed: tpl.committed,
      delivered: Math.floor(tpl.committed * (0.3 + Math.random() * 0.6)),
    })),
  );

export const seedClients: Client[] = [
  {
    id: "acme",
    name: "Acme Corp",
    brandName: "Acme",
    industry: "SaaS",
    website: "https://acme.com",
    primaryContact: "John Carter",
    contactEmail: "john@acme.com",
    contactPhone: "+1 415 555 0123",
    contractStart: "2026-01-01",
    contractEnd: "2026-12-31",
    activeModules: ["social", "paid", "seo", "email"],
    scope: mkScope("acme"),
    credentials: [
      {
        id: "c1",
        category: "social",
        label: "Instagram",
        values: {
          platform: "Instagram",
          profileUrl: "https://instagram.com/acmecorp",
          username: "acmecorp",
          email: "social@acme.com",
          password: "Ac!m3-Insta-2026",
        },
      },
      {
        id: "c2",
        category: "ads",
        label: "Meta Ads Manager",
        values: {
          platform: "Meta Ads",
          accountId: "act_1029384756",
          loginEmail: "ads@acme.com",
          password: "M3ta-Acme-Ad$",
        },
      },
      {
        id: "c3",
        category: "email_tools",
        label: "Mailchimp",
        values: {
          tool: "Mailchimp",
          loginUrl: "https://login.mailchimp.com",
          username: "acmecorp",
          password: "M@ilchimp-2026!",
        },
      },
      {
        id: "c4",
        category: "website",
        label: "acme.com",
        values: {
          websiteUrl: "https://acme.com",
          cmsLogin: "admin",
          cmsPassword: "wpAdmin#2026",
          hostingLogin: "acme-prod",
          hostingPassword: "Host!ng-Pa$$",
          serverLogin: "root",
          domainProvider: "GoDaddy",
        },
      },
    ],
  },
  {
    id: "techflow",
    name: "TechFlow",
    brandName: "TechFlow",
    industry: "Developer Tools",
    website: "https://techflow.io",
    primaryContact: "Priya Mehta",
    contactEmail: "priya@techflow.io",
    contactPhone: "+1 415 555 0144",
    contractStart: "2026-02-01",
    contractEnd: "2027-01-31",
    activeModules: ["social", "seo"],
    scope: mkScope("techflow"),
    credentials: [],
  },
  {
    id: "greenleaf",
    name: "GreenLeaf",
    brandName: "GreenLeaf",
    industry: "Sustainability",
    website: "https://greenleaf.co",
    primaryContact: "Maya Park",
    contactEmail: "maya@greenleaf.co",
    contactPhone: "+1 415 555 0177",
    contractStart: "2025-11-01",
    contractEnd: "2026-10-31",
    activeModules: ["social", "email"],
    scope: mkScope("greenleaf"),
    credentials: [],
  },
];

export const seedCalendarItems: CalendarItem[] = [
  {
    id: "ci-1",
    clientId: "acme",
    module: "social",
    type: "social_post",
    title: "Product launch teaser",
    assignee: "Maya P.",
    date: "2026-06-12",
    time: "10:00",
    taskStatus: "Approved",
    contentStatus: "Scheduled",
    payload: {
      kind: "social",
      data: {
        platform: "Instagram",
        caption: "Something big is coming. Mark your calendars — 06/20. ✨",
        hashtags: "#launch #saas #productlaunch #acme",
        bucket: "Awareness",
        mediaType: "Static",
      },
    },
  },
  {
    id: "ci-2",
    clientId: "acme",
    module: "email",
    type: "email_campaign",
    title: "June Newsletter",
    assignee: "James L.",
    date: "2026-06-14",
    time: "09:00",
    taskStatus: "Internal Review",
    contentStatus: "Draft",
    payload: {
      kind: "email",
      data: {
        segment: "Active Customers",
        subjectLines: [
          "Your June update is here ☀️",
          "What's new at Acme this month",
          "5 features you didn't know about",
        ],
        previewText: "New shortcuts, a fresh template, and a sneak peek of what's next.",
        body: "Hey {{first_name}},\n\nIt's been a busy month at Acme. Here's what's new:\n\n• Faster bulk exports\n• 4 new dashboard templates\n• A first look at our June launch\n\nDive in and let us know what you think.",
        ctaLabel: "See what's new",
        ctaUrl: "https://acme.com/whats-new",
        fromName: "Acme Team",
        fromEmail: "hello@acme.com",
      },
    },
  },
  {
    id: "ci-3",
    clientId: "acme",
    module: "paid",
    type: "paid_ad",
    title: "Retargeting — Free trial",
    assignee: "Alex R.",
    date: "2026-06-13",
    time: "00:00",
    taskStatus: "Client Review",
    contentStatus: "Approved",
    payload: {
      kind: "paid",
      data: {
        platform: "Meta Ads",
        funnelStage: "BOF",
        primaryText: "Still thinking it over? Try Acme free for 14 days — no card required.",
        headline: "Start your free trial",
        description: "Powerful workflows. Zero setup.",
        cta: "Sign Up",
        landingUrl: "https://acme.com/trial",
      },
    },
  },
  {
    id: "ci-4",
    clientId: "acme",
    module: "seo",
    type: "seo_blog",
    title: "10 ways to automate client onboarding",
    assignee: "James L.",
    date: "2026-06-16",
    time: "08:00",
    taskStatus: "In Progress",
    contentStatus: "Draft",
    payload: {
      kind: "seo",
      data: {
        targetKeyword: "automate client onboarding",
        secondaryKeywords: ["client onboarding workflow", "onboarding automation tools"],
        intent: "Informational",
        title: "10 Ways to Automate Client Onboarding in 2026",
        metaTitle: "10 Ways to Automate Client Onboarding (2026 Guide)",
        metaDescription: "Cut onboarding time in half with these 10 automation plays — templates, tools, and step-by-step workflows for agencies.",
        body: "Client onboarding is where great agencies separate themselves from the rest...",
        internalLinks: ["/blog/agency-workflow-templates"],
        externalLinks: ["https://hbr.org/onboarding"],
      },
    },
  },
  {
    id: "ci-5",
    clientId: "acme",
    module: "social",
    type: "social_reel",
    title: "BTS office tour reel",
    assignee: "Chen W.",
    date: "2026-06-18",
    time: "17:00",
    taskStatus: "Internal Review",
    contentStatus: "Draft",
    payload: {
      kind: "social",
      data: {
        platform: "Instagram",
        caption: "A peek inside HQ 👀",
        hashtags: "#bts #teamlife",
        bucket: "Engagement",
        mediaType: "Reel",
      },
    },
  },
  {
    id: "ci-6",
    clientId: "acme",
    module: "website",
    type: "website_update",
    title: "Update pricing page",
    assignee: "Alex R.",
    date: "2026-06-20",
    time: "12:00",
    taskStatus: "Open",
    contentStatus: "Draft",
    payload: {
      kind: "website",
      data: {
        pageUrl: "/pricing",
        changeSummary: "Add new Team plan tier, update FAQ section.",
      },
    },
  },
];
